# Generated by Django 3.2 on 2023-07-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='user',
        ),
    ]
