# Generated by Django 3.2 on 2023-07-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bot', '0002_remove_telegramuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField(default=0)),
                ('short_title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Список тортов',
            },
        ),
    ]
