# Generated by Django 4.1.7 on 2023-07-29 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_bot', '0003_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Торт-ингредиент',
                'verbose_name_plural': 'Торт-ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='CakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Торт-заказ',
                'verbose_name_plural': 'Торт-заказы',
            },
        ),
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('short_title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Список тортов',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=50)),
                ('path', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=30, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField(default=datetime.date.today, verbose_name='Дата исполнения')),
                ('status', models.IntegerField(choices=[(1, 'Принят'), (2, 'Готовиться'), (3, 'Доставка')], verbose_name='Статус заказа')),
                ('comment', models.TextField(default='', max_length=300)),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='Номер клиента'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.CharField(max_length=20, verbose_name='Телеграмм id'),
        ),
        migrations.AddField(
            model_name='orders',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bot.telegramuser', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='cakes',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bot.images'),
        ),
        migrations.AddField(
            model_name='cakeorder',
            name='cake_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bot.cakes'),
        ),
        migrations.AddField(
            model_name='cakeorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bot.orders'),
        ),
        migrations.AddField(
            model_name='cakeingredient',
            name='cake_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bot.cakes'),
        ),
        migrations.AddField(
            model_name='cakeingredient',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bot.ingredients'),
        ),
    ]
