# Generated by Django 4.1.7 on 2023-07-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bot', '0006_remove_orders_price_orders_costs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='Название торта')),
                ('levels_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='Количество уровней')),
                ('levels_shape', models.CharField(choices=[('Круг', 'Круг'), ('Квадрат', 'Квадрат'), ('Прямоугольник', 'Прямоугольник')], default='Круг', max_length=30, verbose_name='Форма уровней')),
                ('cake_writing', models.CharField(blank=True, default='', max_length=250, verbose_name='Надпись на торте')),
                ('ingredients_id', models.ManyToManyField(to='django_bot.ingredients', verbose_name='Ингридиенты')),
            ],
            options={
                'verbose_name': 'Конструктор',
                'verbose_name_plural': 'Торты-конструкторы',
            },
        ),
        migrations.RemoveField(
            model_name='cakeorder',
            name='cake_id',
        ),
        migrations.RemoveField(
            model_name='cakeorder',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='costs',
        ),
        migrations.AddField(
            model_name='orders',
            name='cake_id',
            field=models.ManyToManyField(to='django_bot.cakes'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.CharField(default='', max_length=250, verbose_name='Адрес доставки'),
        ),
        migrations.DeleteModel(
            name='CakeIngredient',
        ),
        migrations.DeleteModel(
            name='CakeOrder',
        ),
    ]
