# Generated by Django 4.1.7 on 2023-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bot', '0008_alter_orders_options_orders_constructor_cake_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cake_id',
            field=models.ManyToManyField(to='django_bot.cakes', verbose_name='Готовые торты'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='constructor_cake_id',
            field=models.ManyToManyField(to='django_bot.constructor', verbose_name='Сконструированные торты'),
        ),
    ]
